name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v6
      - name: Install nodeJS fot lint
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      - name: Lint Javascript
        run: npm run lint:js
      - name: Lint HTML 
        run: npm run lint:html
  
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v6
      - name: Install nodeJS fot lint
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      - name: Security Audit
        run: npm audit --audit-level=high

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v6
      - name: Install nodeJS fot lint
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Example for test
        run: echo "Testing...." 

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ghcr.io/flukekitikorn/e-commerce-website:latest